version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    ports:
      - "6378:6379"
    image: redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379



